var UaInfo=function(){this.uastr=navigator.userAgent;this.uascreen=getscreeninfo();collectUaInfo(this);return this},UaInfo=function(a){this.uastr=a;this.uascreen=getscreeninfo();collectUaInfo(this);return this},UaInfo=function(a,c){this.uastr=a;this.uascreen=c;collectUaInfo(this);return this};logit();
function collectUaInfo(a){"undefined"===typeof a.uastr&&(a.uastr=navigator.userAgent);"undefined"===typeof a.uascreen&&(a.uascreen=getscreeninfo());setDefaultUainfo(a);for(var c=new OSRegxpRule("anroid",["Android (.*?);"],[";.*;( .*) Build/"]),b=new OSRegxpRule("ios",["OS (.*) like Mac OS X"],["\\((.*?);"]),d=new OSRegxpRule("windows phone",["Windows Phone (.*?);"],[".*; (.*)\\)"]),e=new OSRegxpRule("windows destop",["Windows NT (.*); "],[""]),e=[c,b,d,e],c=0;c<e.length;c++)if(b=e[c],d=getRegXpValue(a.uastr,
b.osverregxps,1),0<d.length){c={};c.osname=b.osname;c.osver=d;a.osinfo=c;a.deviceinfo=getRegXpValue(a.uastr,b.deviceinforegxp,1);break}if(""!==a.osinfo){"ios"===a.osinfo.osname&&(a.osinfo.osver=a.osinfo.osver.replace(/_/g,"."));b=[new AppRegxp("wechat","\u5fae\u4fe1",["MicroMessenger/(.*?) "],1),new AppRegxp("weibo","\u5fae\u535a\u624b\u673a\u7aef",["weibo__(.*?)__"],1),new AppRegxp("alipay","\u652f\u4ed8\u5b9d\u624b\u673a\u7aef",["AlipayClient/(.*?) "],1),new AppRegxp("qq","qq\u624b\u673a\u5ba2\u6237\u7aef",
["QQ/(.*?) "],1),new AppRegxp("LBBROWSER","\u730e\u8c79\u6d4f\u89c8\u5668",[" (LBBROWSER)"],9),new AppRegxp("Firefox","\u706b\u72d0\u6d4f\u89c8\u5668",["Firefox/(.*)"],1),new AppRegxp("UCBrowser","UC\u6d4f\u89c8\u5668",["UCBrowser/(.*?) "],1),new AppRegxp("MQQBrowser","QQ\u6d4f\u89c8\u5668(\u79fb\u52a8\u7aef)",["MQQBrowser/(.*?) "],1),new AppRegxp("baidubrowser","\u767e\u5ea6\u6d4f\u89c8\u5668",["baidubrowser/(.*?) "],1),new AppRegxp("MxBrowser","\u9068\u6e38\u4e91\u6d4f\u89c8\u5668",["MxBrowser/(.*)"],
1),new AppRegxp("LieBaoFast","\u730e\u8c79\u6d4f\u89c8\u5668(\u79fb\u52a8\u7aef)",["LieBaoFast/(.*)"],1),new AppRegxp("Mb2345Browser","2345\u6d4f\u89c8\u5668(\u79fb\u52a8\u7aef)",["Mb2345Browser/(.*?)"],1),new AppRegxp("MiuiBrowser","\u5c0f\u7c73\u624b\u673a\u6d4f\u89c8\u5668",["MiuiBrowser/(.*)"],1)];b.sort(function(a,b){return b.prio-a.prio});for(c=0;c<b.length;c++)if(d=b[c],e=getRegXpValue(a.uastr,d.appregxps,1),0<e.length){appinfo={};appinfo.appname=d.appname;appinfo.appver=e;a.appinfo=appinfo;
break}"ios"===a.osinfo.osname&&("wechat"===a.appinfo.appname&&doitatwechat(a),"weibo"===a.appinfo.appname&&doitatweibo(a));setApplePay(a)}}function setApplePay(a){if("ios"===a.osinfo.osname){var c=["iPhone 6S Plus","iphone 6S","iphone 6 plus","iphone 6"],b=[];a.possdevice instanceof Array&&(b=a.possdevice);b.push(a.deviceinfo);for(var d=0;d<b.length;d++)if(in_array(c,b[d])){a.hasApplePay=!0;break}}}
function setDefaultUainfo(a){a.osinfo="";a.deviceinfo="";a.osinfo={osname:"",osver:""};appinfo={appname:"",appver:""};a.appinfo=appinfo;a.hasApplePay=!1}function in_array(a,c){for(var b=0;b<a.length;b++)if(a[b]===c)return!0;return!1}
function doitatweibo(a){var c=getRegXpValue(a.uastr,"Weibo \\((.*)__weibo",1);if(0!==c.length){weidevicelist="iPhone8,2;iPhone 6S Plus;iPhone8,1;iphone 6S;iPhone7,1;iphone 6 plus;iPhone7,2;iphone 6;iPhone6,1;iphone 5s;iPhone6,2;iphone 5s;iPhone5,3;iphone 5c;iPhone5,4;iphone 5c;iPhone5,2;iphone 5;iPhone5,1;iphone 5;iPhone4,1;iphone 4s;iPhone3,3;iphone 4;iPhone3,2;iphone 4;iPhone3,1;iphone 4;iPad5,2;iPad mini 4;iPad5,1;iPad mini 4;iPad4,9;iPad mini 3;iPad4,8;iPad mini 3;iPad4,7;iPad mini 3;iPad4,6;iPad mini 2;iPad4,5;iPad mini 2;iPad4,4;iPad mini 2;iPad2,7;iPad mini;iPad2,6;iPad mini;iPad2,5;iPad mini;iPad5,4;iPad Air 2;iPad5,3;iPad Air 2;iPad4,3;iPad Air;iPad4,2;iPad Air;iPad4,1;iPad Air;iPad3,6;ipad 4;iPad3,5;ipad 4;iPad3,4;ipad 4;iPad3,3;the New iPad;iPad3,2;the New iPad;iPad3,1;the New iPad;iPad2,4;ipad 2;iPad2,3;ipad 2;iPad2,2;ipad 2;iPad2,1;ipad 2;iPad6,8;iPad Pro;iPad6,7;iPad Pro;iPad1,1;ipad 1".split(";");for(var b=
0;b<weidevicelist.length-1;b+=2)weidevicelist[b]===c&&(a.deviceinfo=weidevicelist[b+1])}}
function doitatwechat(a){if("iphone"===a.deviceinfo.toLowerCase())screeninfo="iphone 4;480,320;iphone 4s;480,320;iphone 5;568,320;iphone 5c;568,320;iphone 5s;568,320;iphone 6;667,375;iphone 6s;667,375;iphone 6 plus;736,414;iphone 6 plus;736,414".split(";");else if("ipad"===a.deviceinfo.toLowerCase())screeninfo="ipad 1;1024,768;ipad 2;1024,768;the New iPad;2048,1536;ipad 4;2048,1536;iPad Air;2048,1536;iPad mini;1024,768;iPad Air 2;2048,1536;iPad mini 2;2048,1536;iPad mini 3;2048,1536;iPad mini 4;2048,1536;iPad Pro;2732,2048".split(";");else return;
var c=[];basicscreen=a.uascreen;tagscreen=basicscreen[0]+","+basicscreen[1];for(var b=1;b<screeninfo.length-1;b+=2)screeninfo[b]===tagscreen&&c.push(screeninfo[b-1]);1<c.length&&(a.possdevice=c)}function AppRegxp(a,c,b,d){this.appname=a;this.appdesc=c;this.appregxps=b;this.prio=d;return this}function OSRegxpRule(a,c,b){this.osname=a;this.osverregxps=c;this.deviceinforegxp=b;return this}
function logit(){"localhost"!==location.hostname&&(0===getCookie("uuid").length&&setUid(),screeninfo=getscreeninfo(),uid=getCookie("uid"),picurl="http://col.datatiny.com/log/?screeninfo="+screeninfo+"&uid="+uid,crPic(picurl))}function setUid(){var a=document.createElement("script");a.type="text/javascript";a.src="http://cruid.datatiny.com/uid/";document.getElementsByTagName("head")[0].appendChild(a)}function crPic(a){var c=document.createElement("img");c.src=a;c.style.display="none"}
function getscreeninfo(){var a=[];a.push(screen.height);a.push(screen.width);a.push(screen.availWidth);a.push(screen.availHeight);a.push(screen.colorDepth);a.push(screen.bufferDepth);a.push(screen.deviceXDPI);a.push(screen.deviceYDPI);a.push(screen.logicalXDPI);a.push(screen.logicalYDPI);a.push(screen.fontSmoothingEnabled);a.push(screen.pixelDepth);a.push(screen.updateInterval);return a}
function setcookieY(a,c,b,d){b=new Date;b.setFullYear(b.getFullYear()+50);cookiestr=a+"="+c+";expires="+b+";domain="+d;document.cookie=cookiestr}function getCookie(a){return 0<document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!==c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1===c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""}
function getRegXpValue(a,c,b){b=[];b=c instanceof Array?c:Array(c);if(0===b.length)return"";for(c=0;c<b.length;c++)if(arr=(new RegExp(b[c],"gi")).exec(a),arr instanceof Array&&1<arr.length)return arr[1];return""};